### PR TITLE
refactor : ui

### PR DESCRIPTION
**Pull request by ajaysehwal**
**Description:**
This PR enhances the user experience by improving the election page, profile page, and navbar section. The goal is to create a more user-friendly interface, making navigation and interaction smoother and more intuitive.

**Changes Made:**
I updated the navbar for improved accessibility and design consistency.
I refined the creation page to streamline user interactions.
It enhanced the profiles page for better usability .

Screenshots of the updated user interface 
agora block create election new ui
agorablock profile new ui
argora

### CODE REVIEW

**Comment by Ronnieraj37** [comment]
Please specify what changes you've made along with images of the changes.

**Comment by ajaysehwal** [comment]
sure I will add images and desc , please if there is any group and channel to connect with all contributors so  add me also

**Comment by ajaysehwal** [comment]
demo url : [https://agora-blockchain-demo.vercel.app/](url)

**Comment by Ronnieraj37** [comment]
Impressive work! @ajaysehwal

**Pull request merged**
